### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jeremyworger** [tarepan/rainbowgram#1]
Hey there, will you be releasing your code under any particular license?
Any luck with the inverse icqt? rain2wav?

**Comment by tarepan** [comment]
Thanks for your attention toward this project.  

I will release these codes as loose license, e.g. MIT.  
Now I am busy but I will update the license within these 2 weeks.  
If I forget it two week later and you still have interest to this project, do not hesitate to notice it to me.  

Internally, rain2wav is already working.  
I will update it.

**Comment by jeremyworger** [comment]
Awesome! Sure thing ill let you know.  I am definitely interested in trying it out :)

**Comment by tarepan** [comment]
MIT License was added.  
New API came.  
Thanks for your attention toward this library!
