### ISSUE TITLE
Rain2Wave

### ISSUE THREAD

**Issue by jeremyworger** [tarepan/rainbowgram#2]
Hi Tarepan, thanks for the update in regards to the license for your awesome project.
Is there a way to load the saved image of the rainbowgram (png?) and convert it back to sound? 
Are you still working on the rain2wav function, or am not doing it correctly?
If you do add the rain2wav function, will there be an option to adjust the image resolution in relation to sound? (worse image quality = worse sound quality, better image quality = better sound quality)

**Comment by tarepan** [comment]
# rain2wav from image file
Convert **rainbowgram as NumPy array** back to sound is already implemented (rain2wav).  
Unfortunately, I am not good at image format (jpg, png etc) handling.  
In general, if you are good at image format handling, you can easily convert rainbowgram image back to audio (png -> numpy_array by yourself, numpy_array -> wav by this library).  

# image resolution
I imagine that you think the situation like below.  
get image -> compress image (become low res.) -> convert to audio -> low quality audio  
Is my imagination correct?  

For keeping library simple, I will not implement this type of resolution adjustment.  
But you can easily implement it with several lines of codes.  
Before use rain2wav, you simply interpolate the value and make high resolution one.  
I think [**scipy.interpolate**](https://docs.scipy.org/doc/scipy/reference/interpolate.html) will help you.

**Comment by jeremyworger** [comment]
Unfortunately im not good at python in general haha, but I can ask the community how to go about converting the rainbowgram image back to a numpy array to get it back to sound.  
Yeah I think thats more or less what I mean,  going: audio-->rainbowgram image (variable resolution)-->audio

**Comment by tarepan** [comment]
I hope your project will have good progress!

**Comment by jeremyworger** [comment]
Sorry to ask again. What are the arguments I need to put in the cmd in order to achieve the wav2rain and rain2wav regularly?
